spring:
  application:
    name: api-gateway

server:
  port: 8002 # Port for API Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      preferIpAddress: 13.201.178.199  # Use IP address instead of hostname for registration
